module.exports = [
  {"type":"LECTURE_NOTES","name":"Advanced Algorithms","urls":"https://www.cl.cam.ac.uk/teaching/1819/AdvAlgo","topics":["Data structures and algorithms"],"prerequisites":["Data structures and algorithms"]},
  {"type":"LECTURE_NOTES","name":"Advanced Graphics and Image Processing","urls":"https://www.cl.cam.ac.uk/teaching/1819/AdvGraphIP","topics":["Computer graphics"],"prerequisites":["Computer graphics"]},
  {"type":"LECTURE_NOTES","name":"Further Java","urls":"https://www.cl.cam.ac.uk/teaching/1819/FJava","topics":["Java"],"prerequisites":["Java"]},
  {"type":"LECTURE_NOTES","name":"Further Graphics","urls":"https://www.cl.cam.ac.uk/teaching/1819/FGraphics","topics":["Computer graphics"]},
  {"type":"LECTURE_NOTES","name":"Algorithms:","urls":"https://www.cl.cam.ac.uk/teaching/1819/Algorithms","topics":["Data structures and algorithms"]},
  {"type":"LECTURE_NOTES","name":"Artifical Intelligence","urls":"https://www.cl.cam.ac.uk/teaching/1819/ArtInt","topics":["Artifical Intelligence"],"prerequisites":["Data structures and algorithms"]},
  {"type":"LECTURE_NOTES","name":"Cloud Computing","urls":"https://www.cl.cam.ac.uk/teaching/1819/CloudComp","topics":["Cloud computing"],"prerequisites":["Operating systems","Concurrent, parallel, and distributed systems","Unix"]},
  {"type":"LECTURE_NOTES","name":"Comparative Architectures","urls":"https://www.cl.cam.ac.uk/teaching/1819/CompArch","topics":["Computer engineering"],"prerequisites":["Computer engineering"]},
  {"type":"LECTURE_NOTES","name":"Compiler Construction","urls":"https://www.cl.cam.ac.uk/teaching/1819/CompConstr","topics":["Compiler theory"],"prerequisites":["Ennumerative combinatorics"]},
  {"type":"LECTURE_NOTES","name":"Complexity Theory","urls":"https://www.cl.cam.ac.uk/teaching/1819/Complexity","topics":["Complexity theory"],"prerequisites":["Data structures and algorithms"]},
  {"type":"LECTURE_NOTES","name":"Computation Theory","urls":"https://www.cl.cam.ac.uk/teaching/1819/CompTheory","topics":["Computation Theory"],"prerequisites":["Ennumerative combinatorics"]},
  {"type":"LECTURE_NOTES","name":"Computer Design","urls":"https://www.cl.cam.ac.uk/teaching/1819/CompDesign","topics":["Computer engineering"],"prerequisites":["Electronic engineering"]},
  {"type":"LECTURE_NOTES","name":"Computer Networking","urls":"https://www.cl.cam.ac.uk/teaching/1819/CompNet","topics":["Computer Networks"]},
  {"type":"LECTURE_NOTES","name":"Computer Vision","urls":"http://www.cl.cam.ac.uk/teaching/1819/CompVision","topics":["Computer vision"],"prerequisites":["Machine learning"]},
  {"type":"LECTURE_NOTES","name":"Concepts in Programming Languages","urls":"https://www.cl.cam.ac.uk/teaching/1819/ConceptsPL","topics":["Programming languages and compilers"]},
  {"type":"LECTURE_NOTES","name":"Concurrent and Distributed Systems","urls":"https://www.cl.cam.ac.uk/teaching/1819/ConcDisSys","topics":["Concurrent, parallel, and distributed systems"]},
  {"type":"LECTURE_NOTES","name":"Cryptography","urls":"https://www.cl.cam.ac.uk/teaching/1819/Crypto","topics":["Cryptography"],"prerequisites":["Number theory","Complexity theory"]},
  {"type":"LECTURE_NOTES","name":"Data Science: principles and practice","urls":"https://www.cl.cam.ac.uk/teaching/1819/DataSciII","topics":["Data science"],"prerequisites":["Data science","Machine learning"]},
  {"type":"LECTURE_NOTES","name":"Denotational Semantics","urls":"https://www.cl.cam.ac.uk/teaching/1819/DenotSem","topics":["Denotational Semantics"]},
  {"type":"LECTURE_NOTES","name":"E-Commerce","urls":"https://www.cl.cam.ac.uk/teaching/1819/ECommerce","topics":["E-commerce"],"prerequisites":["Internet security"]},
  {"type":"LECTURE_NOTES","name":"Formal Models of Language","urls":"https://www.cl.cam.ac.uk/teaching/1819/ForModLang","topics":["Formal language theory"],"prerequisites":["Programming languages and compilers"]},
  {"type":"LECTURE_NOTES","name":"Foundation of Computer Science","urls":"https://www.cl.cam.ac.uk/teaching/1819/FoundsCS","topics":["Computer science"]},
  {"type":"LECTURE_NOTES","name":"Foundation of Data Science","urls":"https://www.cl.cam.ac.uk/teaching/1819/DataSci","topics":["Data science"]},
  {"type":"LECTURE_NOTES","name":"Hoare Logic and Model Checking","urls":"https://www.cl.cam.ac.uk/teaching/1819/HLog+ModC","topics":["Hoare Logic"],"prerequisites":["Semantics of Programming Languages"]},
  {"type":"LECTURE_NOTES","name":"Information Theory","urls":"https://www.cl.cam.ac.uk/teaching/1819/InfoTheory","topics":["Information Theory"]},
  {"type":"LECTURE_NOTES","name":"Introduction to Graphics","urls":"https://www.cl.cam.ac.uk/teaching/1819/Graphics","topics":["Computer graphics"]},
  {"type":"LECTURE_NOTES","name":"Machine Learning and Bayesian Inference","urls":"https://www.cl.cam.ac.uk/teaching/1819/MLBayInfer","topics":["Artifical Intelligence",""],"prerequisites":["Artifical Intelligence","Foundations of probability theory"]},
  {"type":"LECTURE_NOTES","name":"Machine Learning and Real-world Data","urls":"https://www.cl.cam.ac.uk/teaching/1819/MLRD","topics":["Machine learning"],"prerequisites":["NST Mathematics"]},
  {"type":"LECTURE_NOTES","name":"Metaprogramming","urls":"https://www.cl.cam.ac.uk/teaching/1819/Metaprog","topics":["Metaprogramming"],"prerequisites":["Prolog","Semantics of programming languages","Programming languages and compilers","Compiler Theory"]},
  {"type":"LECTURE_NOTES","name":"Mobile Robot Systems","urls":"https://www.cl.cam.ac.uk/teaching/1819/MobRobot","topics":["Artificial Intelligence"],"prerequisites":["Data structures and algorithms"]},
  {"type":"LECTURE_NOTES","name":"Mobile and Sensor Systems","urls":"https://www.cl.cam.ac.uk/teaching/1819/MobSensSys","topics":["Sensor systems engineering"],"prerequisites":["Operating systems","Machine learning","Concurrent, parallel, and distributed systems"]},
  {"type":"LECTURE_NOTES","name":"Multicore Semantics and Programming","urls":"https://www.cl.cam.ac.uk/teaching/1819/Multicore","topics":["Multithreading"],"prerequisites":["Enumerative combinatorics","Graph theory","Object-Oriented Programming","Semantics of Programming Languages"]},
  {"type":"LECTURE_NOTES","name":"Natural Language Processing","urls":"https://www.cl.cam.ac.uk/teaching/1819/NLP","topics":["Natural language processing"],"prerequisites":["Machine learning","Programming languages and compilers","Data science","Artifical Intelligence"]},
  {"type":"LECTURE_NOTES","name":"Numerical Analysis","urls":"https://www.cl.cam.ac.uk/teaching/1819/NumAnalys","topics":["Numerical Analysis"]},
  {"type":"LECTURE_NOTES","name":"Object-Oriented Programming","urls":"https://www.cl.cam.ac.uk/teaching/1819/OOProg","topics":["Object-Oriented Programming"]},
  {"type":"LECTURE_NOTES","name":"Operating Systems","urls":"https://www.cl.cam.ac.uk/teaching/1819/OpSystems","topics":["Operating systems"]},
  {"type":"LECTURE_NOTES","name":"Optimising Compilers","urls":"https://www.cl.cam.ac.uk/teaching/1819/OptComp","topics":["Compiler theory"],"prerequisites":["Compiler theory"]},
  {"type":"LECTURE_NOTES","name":"Probability and Computation","urls":"https://www.cl.cam.ac.uk/teaching/1819/Probablty","topics":["Data structures and algorithms"],"prerequisites":["Foundations of Data Science"]},
  {"type":"LECTURE_NOTES","name":"Programming in C and C++","urls":"https://www.cl.cam.ac.uk/teaching/1819/ProgC","topics":["C"],"prerequisites":["C++"]},
  {"type":"LECTURE_NOTES","name":"Quantum Computing","urls":"https://www.cl.cam.ac.uk/teaching/1819/QuantComp","topics":["Quantum computing"],"prerequisites":["Data science","Computation theory"]},
  {"type":"LECTURE_NOTES","name":"Security","urls":"https://www.cl.cam.ac.uk/teaching/1819/Security","topics":["Operating systems security", "Internet security"],"prerequisites":["Operating Systems"]},
  {"type":"LECTURE_NOTES","name":"Semantics of Programming Languages","urls":"https://www.cl.cam.ac.uk/teaching/1819/Semantics","topics":["Semantics of Programming Languages"]},
  {"type":"LECTURE_NOTES","name":"Software and Security Engineering","urls":"https://www.cl.cam.ac.uk/teaching/1819/SWSecEng","topics":["Security"]},
  {"type":"LECTURE_NOTES","name":"Topics in Concurrency","urls":"https://www.cl.cam.ac.uk/teaching/1819/TopConc","topics":["Concurrent, parallel, and distributed systems"],"prerequisites":["Semantics of programming languages"]},
  {"type":"LECTURE_NOTES","name":"Types","urls":"https://www.cl.cam.ac.uk/teaching/1819/Types","topics":["Functional programming"],"prerequisites":["Computation theory"]},
  {"type":"LECTURE_NOTES","name":"Unix Tools","urls":"https://www.cl.cam.ac.uk/teaching/1819/UnixTools","topics":["Unix"]},
  {"type":"LECTURE_NOTES","name":"Digital Electronics","urls":"https://www.cl.cam.ac.uk/teaching/1819/DigElec","topics":["Digital Electronics"]},
  {"type":"ONLINE_COURSE","name":"Algorithms, Part I","urls":"https://www.coursera.org/learn/algorithms-part1","topics":["Data structures and algorithms"]},
  {"type":"ONLINE_COURSE","name":"Algorithms, Part II","urls":"https://www.coursera.org/learn/algorithms-part2","topics":["Data structures and algorithms"],"prerequisites":["Data structures and algorithms"]},
  {"type":"ONLINE_COURSE","name":"An Introduction to Interactive Programming in Python (Part 2)","urls":"https://www.coursera.org/learn/interactive-python-2","topics":["Python"],"prerequisites":["Python"]},
  {"type":"ONLINE_COURSE","name":"An Introduction to Programming the Internet of Things (IOT) ","urls":"https://www.coursera.org/specializations/iot","topics":["Internet of Things","Arduino","Rasberry Pi"]},
  {"type":"ONLINE_COURSE","name":"Bitcoin and Cryptocurrency Technologies","urls":"https://www.coursera.org/learn/cryptocurrency","topics":["Blockchain"]},
  {"type":"ONLINE_COURSE","name":"Build a Modern Computer from First Principles: From Nand to Tetris ","urls":"https://www.coursera.org/learn/build-a-computer","topics":["Computer Engineering","Operating systems", "Programming languages and compilers"]},
  {"type":"ONLINE_COURSE","name":"Cryptography I","urls":"https://www.coursera.org/learn/crypto","topics":["Cryptography"]},
  {"type":"ONLINE_COURSE","name":"Data Structures and Algorithms Specialization","urls":"https://www.coursera.org/specializations/data-structures-algorithms","topics":["Data structures and algorithms"]},
  {"type":"ONLINE_COURSE","name":"Discrete Optimization","urls":"https://www.coursera.org/learn/discrete-optimization","topics":["Discrete optimization"]},
  {"type":"ONLINE_COURSE","name":"Improving Deep Neural Networks: Hyperparameter tuning, Regularization and Optimization","urls":"https://www.coursera.org/learn/deep-neural-network","topics":["Neural networks"],"prerequisites":["Neural networks"]},
  {"type":"ONLINE_COURSE","name":"Introduction to Data Science in Python","urls":"https://www.coursera.org/learn/python-data-analysis","topics":["Data science"]},
  {"type":"ONLINE_COURSE","name":"Java Programming and Software Engineering Fundamentals","urls":"https://www.coursera.org/specializations/java-programming","topics":["Java"]},
  {"type":"ONLINE_COURSE","name":"Neural Networks and Deep Learning","urls":"https://www.coursera.org/learn/neural-networks-deep-learning","topics":["Neural networks"]},
  {"type":"ONLINE_COURSE","name":"Object Oriented Java Programming: Data Structures and Beyond Specialization","urls":"https://www.coursera.org/specializations/java-object-oriented","topics":["Object-Oriented Programming","Java"]},
  {"type":"ONLINE_COURSE","name":"Programming Languages, Part A","urls":"https://www.coursera.org/learn/programming-languages","topics":["Programming languages and compilers"]},
  {"type":"ONLINE_COURSE","name":"Programming Languages, Part B","urls":"https://www.coursera.org/learn/programming-languages-part-b","topics":["Programming languages and compilers"],"prerequisites":["Programming languages and compilers"]},
  {"type":"ONLINE_COURSE","name":"Python Data Structures","urls":"https://www.coursera.org/learn/python-data","topics":["Python"]},
  {"type":"ONLINE_COURSE","name":"Ruby on Rails Web Development Specialization","urls":"https://www.coursera.org/specializations/ruby-on-rails","topics":["Web development","Ruby on Rails"]},
  {"type":"ONLINE_COURSE","name":"Using Python to Access Web Data","urls":"https://www.coursera.org/learn/python-network-data","topics":["Python","Web scraping"]},
  {"type":"ONLINE_COURSE","name":"Angular 7 (formerly Angular 2) - The Complete Guide","urls":"https://www.udemy.com/the-complete-guide-to-angular-2/","topics":["Angular.js"]},
  {"type":"ONLINE_COURSE","name":"Automate the Boring Stuff with Python Programming","urls":"https://www.udemy.com/automate/","topics":["Python 3"]},
  {"type":"ONLINE_COURSE","name":"Build Responsive Real World Websites with HTML5 and CSS3","urls":"https://www.udemy.com/design-and-develop-a-killer-website-with-html5-and-css3/","topics":["HTML5","CSS3"]},
  {"type":"ONLINE_COURSE","name":"Complete C# Unity Developer 2D: Learn to Code Making Games","urls":"https://www.udemy.com/unitycourse/","topics":["Unity","C#"]},
  {"type":"ONLINE_COURSE","name":"Complete Python Bootcamp: Go from zero to hero in Python 3","urls":"https://www.udemy.com/complete-python-bootcamp/","topics":["Python 3"]},
  {"type":"ONLINE_COURSE","name":"Docker Mastery: The Complete Toolset From a Docker Captain","urls":"https://www.udemy.com/docker-mastery/","topics":["Docker"]},
  {"type":"ONLINE_COURSE","name":"Java Programming Masterclass for Software Developers","urls":"https://www.udemy.com/java-the-complete-java-developer-course/","topics":["Java"]},
  {"type":"ONLINE_COURSE","name":"JavaScript: Understanding the Weird Parts","urls":"https://www.udemy.com/understand-javascript/","topics":["Javascript"]},
  {"type":"ONLINE_COURSE","name":"Learn Python Programming Masterclass","urls":"https://www.udemy.com/python-the-complete-python-developer-course/","topics":["Python 3"]},
  {"type":"ONLINE_COURSE","name":"Learn and Understand NodeJS","urls":"https://www.udemy.com/understand-nodejs/","topics":["Node.js"]},
  {"type":"ONLINE_COURSE","name":"Learning Python for Data Analysis and Visualization","urls":"https://www.udemy.com/learning-python-for-data-analysis-and-visualization/","topics":["Python 3"]},
  {"type":"ONLINE_COURSE","name":"Machine Learning, Data Science and Deep Learning with Python","urls":"https://www.udemy.com/data-science-and-machine-learning-with-python-hands-on/","topics":["Machine learning","Data science","Python 3"]},
  {"type":"ONLINE_COURSE","name":"Modern JavaScript (from Novice to Ninja)","urls":"https://www.udemy.com/modern-javascript-from-novice-to-ninja/","topics":["Javascript"]},
  {"type":"ONLINE_COURSE","name":"Modern React with Redux [2019 Update]","urls":"https://www.udemy.com/react-redux/","topics":["React","React Redux", "Redux"]},
  {"type":"ONLINE_COURSE","name":"React - The Complete Guide","urls":"https://www.udemy.com/react-the-complete-guide-incl-redux/","topics":["React","React Router", "React Redux", "Redux"]},
  {"type":"ONLINE_COURSE","name":"The Complete Android N Developer Course","urls":"https://www.udemy.com/complete-android-n-developer-course/","topics":["Java","Android"]},
  {"type":"ONLINE_COURSE","name":"The Complete JavaScript Course 2019: Build Real Projects!","urls":"https://www.udemy.com/the-complete-javascript-course/","topics":["Javascript"]},
  {"type":"ONLINE_COURSE","name":"The Complete Node.js Developer Course (3rd Edition)","urls":"https://www.udemy.com/the-complete-nodejs-developer-course-2/","topics":["Node.js","Express.js","MongoDB","Mocha"]},
  {"type":"ONLINE_COURSE","name":"The Complete React Native and Redux Course","urls":"https://www.udemy.com/the-complete-react-native-and-redux-course/","topics":["React Native","React Redux", "Redux"]},
  {"type":"ONLINE_COURSE","name":"The Complete Web Developer Course 2.0","urls":"https://www.udemy.com/the-complete-web-developer-course-2/","topics":["HTML","CSS","Javascript","PHP","Python","MySQL"]},
  {"type":"ONLINE_COURSE","name":"The Python Mega Course: Build 10 Real World Applications","urls":"https://www.udemy.com/the-python-mega-course/","topics":["Python 3","Data science"]},
  {"type":"ONLINE_COURSE","name":"The Ultimate MySQL Bootcamp: Go from SQL Beginner to Expert","urls":"https://www.udemy.com/the-ultimate-mysql-bootcamp-go-from-sql-beginner-to-expert/","topics":["SQL","MySQL"]},
  {"type":"ONLINE_COURSE","name":"The Web Developer Bootcamp","urls":"https://www.udemy.com/the-web-developer-bootcamp/","topics":["HTML","CSS","Javascript","Node.js"]},
  {"type":"ONLINE_COURSE","name":"Unreal Engine C++ Developer: Learn C++ and Make Video Games","urls":"https://www.udemy.com/unrealcourse/","topics":["Unreal Engine 4","C++"]},
  {"type":"ONLINE_COURSE","name":"Vue JS 2 - The Complete Guide (incl. Vue Router & Vuex)","urls":"https://www.udemy.com/vuejs-2-the-complete-guide/","topics":["Vue.js"]},
  {"type":"ONLINE_COURSE","name":"iOS 11 & Swift 4 - The Complete iOS App Development Bootcamp","urls":"https://www.udemy.com/ios11-app-development-bootcamp/","topics":["iOS","Swift"]},
  {"type":"ONLINE_COURSE","name":"AWS Certified Developer - Associate 2019","urls":"https://www.udemy.com/aws-certified-developer-associate/","topics":["Amazon Web Services"]},
  {"type":"ONLINE_COURSE","name":"AWS Certified Solutions Architect - Associate 2019","urls":"https://www.udemy.com/aws-certified-solutions-architect-associate/","topics":["Amazon Web Services"]},
  {"type":"ONLINE_COURSE","name":"AWS Certified SysOps Administrator - Associate 2019","urls":"https://www.udemy.com/aws-certified-sysops-administrator-associate/","topics":["Amazon Web Services"]},
  {"type":"ONLINE_COURSE","name":"AZ-300 Azure Architecture Technologies Certification Exam","urls":"https://www.udemy.com/70534-azure/","topics":["Azure"]},
  {"type":"ONLINE_COURSE","name":"Agile Crash Course: Agile Project Management; Agile Delivery","urls":"https://www.udemy.com/course/agile-crash-course/","topics":["Agile"]},
  {"type":"ONLINE_COURSE","name":"Amazon Web Services (AWS) Certified 2019 - 4 Certifications!","urls":"https://www.udemy.com/aws-certified-associate-architect-developer-sysops-admin/","topics":["Amazon Web Services"]},
  {"type":"ONLINE_COURSE","name":"Blockchain and Bitcoin Fundamentals","urls":"https://www.udemy.com/blockchain-and-bitcoin-fundamentals/","topics":["Blockchain","Bitcoin"]},
  {"type":"ONLINE_COURSE","name":"CCNA 2018 200-125","urls":"https://www.udemy.com/ccna-on-demand-video-boot-camp/","topics":["Computer networks","Computer Engineering"]},
  {"type":"ONLINE_COURSE","name":"Cisco CCNA 200-125 – The Complete Guide to Getting Certified","urls":"https://www.udemy.com/course/ccna-complete/","topics":["Computer networks","Computer Engineering"]},
  {"type":"ONLINE_COURSE","name":"CompTIA A+ Certification 901. The Total Course","urls":"https://www.udemy.com/comptia-a-901-the-total-course/","topics":["Computer networks"]},
  {"type":"ONLINE_COURSE","name":"CompTIA Security+ Certification (SY0-501): The Total Course","urls":"https://www.udemy.com/comptia-security-certification-sy0-501-the-total-course/","topics":["Internet security"]},
  {"type":"ONLINE_COURSE","name":"Data Structures & Algorithms - Interview !!","urls":"https://www.udemy.com/course/learn-data-structure-algorithms-with-java-interview/","topics":["Data structures and algorithms"]},
  {"type":"ONLINE_COURSE","name":"Learn Ethical Hacking From Scratch","urls":"https://www.udemy.com/learn-ethical-hacking-from-scratch/","topics":["Internet security"]},
  {"type":"ONLINE_COURSE","name":"Learn Linux in 5 Days and Level Up Your Career","urls":"https://www.udemy.com/learn-linux-in-5-days/","topics":["Linux"]},
  {"type":"ONLINE_COURSE","name":"Linux Administration Bootcamp: Go from Beginner to Advanced","urls":"https://www.udemy.com/linux-administration-bootcamp/","topics":["Linux"]},
  {"type":"ONLINE_COURSE","name":"Linux Command Line Basics","urls":"https://www.udemy.com/linux-command-line-volume1/","topics":["Linux"]},
  {"type":"ONLINE_COURSE","name":"PLC Programming From Scratch (PLC I)","urls":"https://www.udemy.com/plc-programming-from-scratch/","topics":["Programmable logic controller"]},
  {"type":"ONLINE_COURSE","name":"Spring Framework Master Class","urls":"https://www.udemy.com/spring-tutorial-for-beginners/","topics":["Spring"],"prerequisites":["Java"]},
  {"type":"ONLINE_COURSE","name":"The Complete Cyber Security Course","urls":"https://www.udemy.com/the-complete-internet-security-privacy-course-volume-1/","topics":["Internet security"]},
  {"type":"ONLINE_COURSE","name":"The Complete Ethical Hacking Course: Beginner to Advanced!","urls":"https://www.udemy.com/penetration-testing/","topics":["Internet security"]},
  {"type":"ONLINE_COURSE","name":"The Complete Networking Fundamentals Course. Your CCNA start","urls":"https://www.udemy.com/complete-networking-fundamentals-course-ccna-start/","topics":["Computer networks"]},
  {"type":"ONLINE_COURSE","name":"The Complete Oracle SQL Certification Course","urls":"https://www.udemy.com/course/the-complete-oracle-sql-certification-course/","topics":["Oracle SQL"]},
]